{
 "title": "crypto_prices",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MARKET OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Biggest Looser ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coin as 'Coin', price_change_pct as 'Percent Change'\r\nFROM prices\r\nWHERE fetched_at IN (\r\n    SELECT MAX(fetched_at)\r\n    FROM prices\r\n    GROUP BY coin\r\n)\r\nORDER BY price_change_pct ASC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "CURRENT PRICES",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT price_usd as btc FROM crypto_tracker.prices WHERE coin = 'btc' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_usd as eth FROM crypto_tracker.prices WHERE coin = 'eth' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_usd as sol FROM crypto_tracker.prices WHERE coin = 'sol' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_usd as bnb FROM crypto_tracker.prices WHERE coin = 'bnb' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_usd as xrp FROM crypto_tracker.prices WHERE coin = 'xrp' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_change_pct as btc_change FROM crypto_tracker.prices WHERE coin = 'btc' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_change_pct as eth_change FROM crypto_tracker.prices WHERE coin = 'eth' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_change_pct as sol_change FROM crypto_tracker.prices WHERE coin = 'sol' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_change_pct as bnb_change FROM crypto_tracker.prices WHERE coin = 'bnb' ORDER BY fetched_at DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT price_change_pct as xrp% FROM crypto_tracker.prices WHERE coin = 'xrp' ORDER BY fetched_at DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Buy Signal in 24h Range",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coin,\r\nROUND(100 - ((price_usd - low_24h) / (high_24h - low_24h)) * 100, 2) AS buy_signal\r\nFROM prices\r\nWHERE fetched_at IN (\r\n    SELECT MAX(fetched_at)\r\n    FROM prices\r\n    GROUP BY coin\r\n)\r\nORDER BY buy_signal DESC;"
    }
   ]
  },
  {
   "title": "Current Biggest Gainer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coin as 'Coin', price_change_pct as 'Percent Change'\r\nFROM prices\r\nWHERE fetched_at IN (\r\n    SELECT MAX(fetched_at)\r\n    FROM prices\r\n    GROUP BY coin\r\n)\r\nORDER BY price_change_pct DESC\r\nLIMIT 1;"
    }
   ]
  },
  { "title": "ANALYTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Most Volatile Coin Right Now",
   "type": "bargauge",
   "description": "Live bar gauge ranking all 5 cryptocurrencies by 24h price change percentage, updated every 5 minute",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT coin, price_change_pct\r\nFROM prices\r\nWHERE fetched_at IN (\r\n    SELECT MAX(fetched_at) \r\n    FROM prices \r\n    GROUP BY coin\r\n)\r\nORDER BY price_change_pct DESC;"
    }
   ]
  },
  {
   "title": "Crypto Price Time Series Visualisation",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 6, "y": 14 },
   "targets": [
    {
     "dataset": "crypto_tracker",
     "rawSql": "SELECT fetched_at, price_usd as btc_usd FROM crypto_tracker.prices\r\nWHERE coin = 'btc'\r\nLIMIT 50 "
    },
    {
     "dataset": "crypto_tracker",
     "rawSql": "SELECT fetched_at, price_usd as eth_usd FROM crypto_tracker.prices \r\nWHERE coin = 'eth'\r\nLIMIT 50 "
    },
    {
     "dataset": "crypto_tracker",
     "rawSql": "SELECT fetched_at, price_usd as sol_usd FROM crypto_tracker.prices \r\nWHERE coin = 'sol'\r\nLIMIT 50 "
    },
    {
     "dataset": "crypto_tracker",
     "rawSql": "SELECT fetched_at, price_usd as bnb_usd FROM crypto_tracker.prices \r\nWHERE coin = 'bnb'\r\nLIMIT 50 "
    },
    {
     "dataset": "crypto_tracker",
     "rawSql": "SELECT fetched_at, price_usd as xrp_usd FROM crypto_tracker.prices \r\nWHERE coin = 'xrp'\r\nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Trading Volume Distribution Across Cryptocurrencies",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT coin, volume_24h\r\nFROM prices\r\nWHERE fetched_at IN (\r\n    SELECT MAX(fetched_at)\r\n    FROM prices\r\n    GROUP BY coin\r\n)"
    }
   ]
  }
 ]
}